console.log('Hello, world!!');
const h1 = document.querySelector('h1');
console.log('The h1: ', h1);
console.dir(h1);
const explain = document.querySelector('#explanation');
console.log('The #explaination: ', explain);
console.dir(explain);
const hint = document.querySelector('.hint');
console.log('The .hint: ', hint);
console.dir(hint);
const p = document.querySelectorAll('p');
console.log('All p: ', p);
const example = document.querySelectorAll('.example-link');
console.log('All example-link: ', example);
